name: image recognition app 

on:
    push:
        branches: [ "main" ]

    pull_request:
        branches: [ "main" ]

jobs:
    test-and-build:
        runs-on: ubuntu-latest

        steps:
            - name: action checkout code
              uses: actions/checkout@v4
            
            - name: setup python "3.12.7"
              uses: actions/setup-python@v4
              with:
                python-version: "3.12.7"
            
            - name: installing dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: test with pytest
              run: |
                pytest